server:
  port: 9999
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "never"
    prometheus:
      access: read_only
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus

springdoc:
  packagesToScan: uk.gov.moj.cp.controllers
  writer-with-order-by-keys: true

logging:
  level:
    uk.gov.moj.cp: ${TMC_LOGGING_LEVEL:INFO}

tmc:
  aws:
    enabled: ${TMC_AWS_SECRET_MANAGER_ENABLED:true}
    secret-name: ${TMC_AWS_SECRET_MANAGER_NAME}
    region: ${TMC_AWS_REGION:${AWS_REGION:eu-west-2}}

spring:
  config:
    import: "optional:configtree:/mnt/secrets/rpe/"
  application:
    name: Spring Boot Template
  datasource:
    url: ${TMC_DB_URL}
    username: ${TMC_DB_USERNAME}
    password: ${TMC_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

services:
  amp-url: ${TMC_AMP_URL}
  slc-amp-subscription-key: ${TMC_SLC_AMP_SUBSCRIPTION_KEY}
  rcc-amp-subscription-key: ${TMC_RCC_AMP_SUBSCRIPTION_KEY}
  pcd-amp-subscription-key: ${TMC_PCD_AMP_SUBSCRIPTION_KEY}

  api-cp-refdata-courthearing-courthouses-courtrooms:
    path: /rcc/courthouses/{court_id}/courtrooms/{court_room_id}

  api-cp-refdata-courthearing-courthouses:
    path: /rcc/courthouses/{court_id}

  api-cp-crime-schedulingandlisting-courtschedule:
    path: /slc/case/{case_urn}/courtschedule

  api-cp-pcd-prosecution-case-details:
    path: /pcd/cases/{case_urn}

  refdata-courthearing-judges:
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-refdata-courthearing-judges
    version: 0.3.10

  crime-cases:
    path: /cases/{case_id}/results
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-courthearing-cases
    version: 0.7.1

  users:
    authorization-header: ${TMC_SECURITY_JWT_TOKEN}
    aes-encryption-secret: ${TMC_AES_ENCRYPTION_SECRET}
    hmac-encryption-secret: ${TMC_HMAC_ENCRYPTION_SECRET}

  oauth-token:
    path: /{tenant_id}/oauth2/{version}/token
    version: v2.0
    url: ${TMC_TOKEN_URL}
    tenant-id: ${TMC_TOKEN_TENANT_ID}
    client-id: ${TMC_TOKEN_CLIENT_ID}
    client-secret: ${TMC_TOKEN_CLIENT_SECRET}
    prosecution-case-scope: ${TMC_PCD_TOKEN_SCOPE}
    court-schedule-scope: ${TMC_SLC_TOKEN_SCOPE}
    reference-data-scope: ${TMC_RCC_TOKEN_SCOPE}
    cache:
      # 8 hours originally, we set 6 hours
      token-cache-ttl-minutes: ${TMC_TOKEN_CACHE_TTL_MINUTES:360}

  rate-limit:
    # Token bucket rate limiting:
    # - Each external API request consumes 1 token
    # - Each user can accumulate up to 300 tokens
    # - The bucket is refilled with 150 tokens every 5 minutes (equivalent to 1 token every 2 seconds)
    # - Once the bucket reaches 300 tokens, no additional tokens are added
    maximum-tokens-capacity: ${TMC_RATE_LIMIT_MAXIMUM_TOKENS_CAPACITY:300}
    refill-tokens: ${TMC_RATE_LIMIT_REFILL_TOKENS:150}
    refill-period-minutes: ${TMC_RATE_LIMIT_REFILL_PERIOD_MINUTES:5}
