spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: true
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

tmc:
  aws:
    enabled: false

services:
  amp-url: https://dummy
  slc-amp-subscription-key: dummy-slc-amp-subscription-key
  rcc-amp-subscription-key: dummy-rcc-amp-subscription-key
  pcd-amp-subscription-key: dummy-pcd-amp-subscription-key
  api-cp-crime-schedulingandlisting-courtschedule:
    path: /some-api-cp-crime-schedulingandlisting-courtschedule
  api-cp-refdata-courthearing-courthouses:
    path: /some-api-cp-refdata-courthearing-courthouses
  api-cp-pcd-prosecution-case-details:
    path: /cases/{case_urn}
  users:
    authorization-header: test-token
    aes-encryption-secret: FmkCWyCPfsuVD3r1SHqS3BFtB4YI1i7QdiZrfGKjv4k=
    hmac-encryption-secret: oUO29pYYc9n4XlvAbPt8B0ncfadyqnI8C63tKCWKuao=
  oauth-token:
    url: https://login.microsoftonline.com
    path: /{tenant}/oauth2/{version}/token
    tenant-id: tenant
    version: v2.0
    client-id: client-id
    client-secret: client-secret
    prosecution-case-scope: api://scope/.default
    court-schedule-scope: api://scope/.default
    reference-data-scope: api://scope/.default

  rate-limit:
    maximum-tokens-capacity: ${TMC_RATE_LIMIT_MAXIMUM_TOKENS_CAPACITY:20}
    refill-tokens: ${TMC_RATE_LIMIT_REFILL_TOKENS:10}
    refill-period-minutes: ${TMC_RATE_LIMIT_REFILL_PERIOD_MINUTES:1}
